:includedir: ../../../../../../..
:relrootdir: ../../../../../../..
:term: JsonMapper
= {term}

The {term} class is the central location for configuring Jackson for reading and writing JSON structures.

[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-api/src/main/java/esy/json/JsonMapper.java[tags=configure,indent=0]
----
<1> The `Jdk8Module` ensures that data types like `Optional` are correctly serialized.

<2> The `JavaTimeModule` ensures that temporal data types like `LocalDate` are correctly serialized.

<3> With the value `false`, it is ensured that during PATCH operations the list from the JSON structure is merged with the list from the database. +
The behavior for lists is thus consistent with the behavior for values. +
See also annotation `@JsonMerge`.

<4> With the value `Include.NON_NULL` only properties with non-null values are serialized.

<5> With the value `true`, temporal data types are serialized with timezone.

<6> With the value `false`, temporal data types are serialized with formatted text.

<7> With the value `false`, serialization is made robust. +
Unknown properties are ignored.

This method initializes the _Jackson Object Mapper_.
It is used in the `EndpointConfiguration` class to uniformly define behavior in the _Spring Framework_.
It is used in classes like `JsonJpaEntity` to implement `parseJson` and `writeJson` operations.
