= AI-driven development and maintenance

== Sanity Check of the domain model

.Prompt
----
@copilot check domain entities
----

The agent reviews implementation files for all domain entities and ensures REST endpoints and GraphQL operations are up-to-date, fixes minor issues or leaves hints and instructions to fix issues.

You may reduce the scope to changes files of a pull request.

== Sanity Check of REST API documentation

.Prompt
----
@copilot check rest api documentation
----

The agent reviews implementation files for all REST API endpoints and ensures related REST API documentation is up-to-date, fixes minor issues or leaves hints and instructions to fix issues.

You may reduce the scope to changes files of a pull request.

== Create new REST API documentation

.Prompt
----
@copilot create rest api documentation for owner endpoints
----

The agent reviews implementation files for all REST API endpoints for the given main entity and creates a new documentation following structure and instructions of the template.
Replace `owner` with the name of the main entity.

== Sanity Check of GraphQL API documentation

.Prompt
----
@copilot check graphql api documentation
----

The agent reviews implementation files for all GraphQL API operations and ensures related GraphQL API documentation is up-to-date, fixes minor issues or leaves hints and instructions to fix issues.

You may reduce the scope to changes files of a pull request.

== Create new GraphQL API documentation

.Prompt
----
@copilot create graphql api documentation for owner operations
----

The agent reviews implementation files for all GraphQL API operations for the given main entity and creates a new documentation following structure and instructions of the template.
Replace `owner` with the name of the main entity.
