:icons: font
:experimental: true
= Self-Contained System with Spring Boot backend and browser-based clients

== Applications

=== app/server

Backend server of the application with a HSQL database.

https://spring.io/projects/spring-boot

http://hsqldb.org

=== app/client-angular

Browser-based web client of the application.

https://angular.dev

https://tailwindcss.com

=== app/client-svelte

Browser-based web client of the application.

https://svelte.dev

https://tailwindcss.com

https://vitejs.dev

=== app/deploy

Local deployment of the application.

https://www.docker.com/

https://rancherdesktop.io/

== Libraries

=== lib/backend-api

Data model for the backend server of the application.

https://projectlombok.org/

https://github.com/FasterXML/jackson-docs

=== lib/backend-data

REST API for the backend server of the application.

https://spring.io/projects/spring-framework

https://spring.io/projects/spring-restdocs

https://spring.io/projects/spring-data-jpa

https://spring.io/projects/spring-data-rest

https://docs.liquibase.com/home.html

== Versioning

The application versioning is based on
https://git-scm.com/book/en/v2/Git-Basics-Tagging[_lightweight tags_]
in the repository and follows the concept of
https://semver.org/[_semantic versioning_]
with major and minor numbers.
A patch number is only used for internal purposes.

[source, gradle]
----
./gradlew versionTag
----

This command shows the current version of the application.

The change history is based on the
https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History[_commit history_]
of the repository and follows the concept of
https://www.conventionalcommits.org/[_conventional commits_]
for describing changes.

[source, gradle]
----
./gradlew versionRelease
----

This command shows a list of changes in the current release.
The list can also be empty.

[source, gradle]
----
./gradlew versionHistory
----

This command shows all changes from past releases grouped by version and sorted in descending order.

The current version with major and minor number is entered in the `VERSION` file.

WARNING: The file must not contain a line break.

Additionally, the current version must be entered in other files, e.g., in `package.json` or `Chart.yaml`.

[source, gradle]
----
./gradlew versionCheck
----

This command checks whether all entered versions with major and minor numbers match exactly.

== Frequently Asked Questions

=== Building and testing code

[source, npm]
----
npm install --prefix app/client-angular
npm install --prefix app/client-svelte
----

[source, gradle]
----
./gradlew clean build
----

[source, gradle]
----
./gradlew buildImage
----

[source, gradle]
----
./gradlew pages
----

=== Formatting code

[source, gradle]
----
./gradlew format
----

=== Starting Spring Boot server locally

[source, gradle]
----
./gradlew app:server:bootRun
----

This command starts the server as a Java application.
The HAL Explorer is accessed in the browser at `localhost:8080/api/explorer`.
The GraphQL Explorer is accessed in the browser at `localhost:8080/api/graphiql`.

The environment variable `LOGGING_LEVEL_ORG_HIBERNATE_TYPE` can be used to control the output of type information.
With the value `TRACE`, for example, the current parameters of statements are output.

The environment variable `LOGGING_LEVEL_ORG_HIBERNATE_STAT` can be used to control the output of statistics.
With the value `DEBUG`, for example, the metrics of statements are output.

=== Starting Angular client locally

[source, npm]
----
npm run start --prefix app/client-angular
----

This command starts the client as a Node application.
The Angular client is accessed in the browser at `localhost:5052`.

=== Starting Svelte client locally

[source, npm]
----
npm run start --prefix app/client-svelte
----

This command starts the client as a Node application.
The Svelte client is accessed in the browser at `localhost:5050`.

=== Starting application locally

[source, gradle]
----
./gradlew composeUp
----

This command starts clients and server locally.
The Angular client is accessed in the browser at `localhost:5052`.
The Svelte client is accessed in the browser at `localhost:5050`.

[source, gradle]
----
./gradlew composeDown
----

This command stops clients and server.

=== Testing application locally

[source, gradle]
----
sh playwright.setup.sh
----

This command installs the browsers for testing with Playwright.

[source, gradle]
----
sh playwright.test.sh
----

This command starts the application and runs end-to-end tests with Playwright.
At the end, the application is shut down - even in case of errors.
