:icons: font
:experimental: true
= Self-Contained System mit Spring-Boot und Svelte-UI

== Projekte

=== app/backend-api

Datenmodell für den Spring-Boot-Server der Anwendung.

https://projectlombok.org/

https://github.com/FasterXML/jackson-docs

=== app/backend-data

REST-API für den Spring-Boot-Server der Anwendung.

https://spring.io/projects/spring-framework

https://spring.io/projects/spring-restdocs

https://spring.io/projects/spring-data-jpa

https://spring.io/projects/spring-data-rest

https://docs.liquibase.com/home.html

=== app/server

Spring-Boot-Server der Anwendung mit einer HSQL-Datenbank.

https://spring.io/projects/spring-boot

http://hsqldb.org

=== app/client

Browser-basierter Svelte-Client der Anwendung.

https://svelte.dev

https://tailwindcss.com

https://visionmedia.github.io/page.js

https://vitejs.dev

=== app/deploy

Lokales Deployment der Anwendung.

https://www.docker.com/

https://rancherdesktop.io/

== Häufig gestellte Fragen

=== Code bauen und testen

[source, npm]
----
npm install --prefix app/client
----

[source, gradle]
----
./gradlew clean build
----

[source, gradle]
----
./gradlew buildImage
----

=== Code formatieren

[source, gradle]
----
./gradlew format
----

=== Spring-Boot-Server lokal starten

[source, gradle]
----
./gradlew app:server:bootRun
----

Der Befehl startet den Server als Java-Anwendung.
Der HAL-Explorer wird im Browser mit `localhost:8080/api/explorer` aufgerufen.
Der GraphQl-Explorer wird im Browser mit `localhost:8080/api/graphiql` aufgerufen.

Mit der Umgebungsvariable `LOGGING_LEVEL_ORG_HIBERNATE_TYPE` kann die Ausgabe von Typinformationen gesteuert werden.
Mit dem Wert `TRACE` werden bspw. die aktuellen Parameter von Statements ausgegeben.

Mit der Umgebungsvariable `LOGGING_LEVEL_ORG_HIBERNATE_STAT` kann die Ausgabe von Statistiken gesteuert werden.
Mit dem Wert `DEBUG` werden bspw. die Kennzahlen von Statements ausgegeben.

[source, gradle]
----
./gradlew app:server:dockerRun
----

Der Befehl startet den Server als Container.
Der HAL-Explorer wird im Browser mit `localhost:8080/api/explorer` aufgerufen.
Der GraphQl-Explorer wird im Browser mit `localhost:8080/api/graphiql` aufgerufen.

=== Svelte-Client lokal starten

[source, npm]
----
npm run dev --prefix app/client
----

Der Befehl startet den Client als Node-Anwendung.
Die Anwendung wird im Browser mit `localhost:5000` aufgerufen.

[source, gradle]
----
./gradlew app:client:dockerRun
----

Der Befehl startet den Client als Container.
Die Anwendung wird im Browser mit `localhost:5000` aufgerufen.

=== Anwendung lokal starten

[source, gradle]
----
./gradlew composeup
----

Der Befehlt startet Client und Server lokal.
Die Anwendung wird im Browser mit `localhost:5000` aufgerufen.

[source, gradle]
----
./gradlew composedown
----

Der Befehlt stoppt Client und Server.
