:includedir: ../..
:relrootdir: ../..
:restdocdir: {includedir}/lib/backend-data/build/generated-snippets
= Owner REST API

REST-API for managing pet owners acting as clients in the pet clinic application.
It provides standard CRUD operations and a search endpoint that returns items.

== Model

=== Owner

include::{includedir}/lib/backend-api/src/main/java/esy/api/client/Owner.adoc[]

The liquibase script defines the database table.

.Liquibase
[source,xml,options="nowrap"]
----
include::{includedir}/lib/backend-data/src/main/resources/liquibase/v1/owner.xml[]
----

The entity class `Owner` is the aggregate root.

.Entity
[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-api/src/main/java/esy/api/client/Owner.java[indent=0,tags=properties]
----

The item class `OwnerItem` is a simplified representation of an entity `Owner` for item selection purposes.

.Item
[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-api/src/main/java/esy/api/client/OwnerItem.java[indent=0,tags=properties]
----

=== Pet

include::{includedir}/lib/backend-api/src/main/java/esy/api/client/Pet.adoc[]

The entity class `Pet` is referenced.
A pet belongs to exactly one owner.

.Entity
[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-api/src/main/java/esy/api/client/Pet.java[indent=0,tags=properties]
----

The item class `PetItem` is a simplified representation of the entity `Pet` for item selection purposes.

.Item
[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-api/src/main/java/esy/api/client/PetItem.java[indent=0,tags=properties]
----

== Operations

=== `POST /api/owner`

This operation creates a new entity `Owner`.

****

.Command
include::{restdocdir}/post-api-owner/curl-request.adoc[]

.Request
include::{restdocdir}/post-api-owner/http-request.adoc[]

.Response
include::{restdocdir}/post-api-owner/response-body.adoc[]

****

This operation reports `Created` or code 201 if the entity was successfully created.

This operation reports `Bad Request` or code 400 if the data was not processed.

This operation reports `Conflict` or code 409 if a unique constraint would be violated.

=== `PUT /api/owner/{id}`

This operation updates an existing entity `Owner` or creates a new one.

****

.Command
include::{restdocdir}/put-api-owner/curl-request.adoc[]

.Request
include::{restdocdir}/put-api-owner/http-request.adoc[]

.Response
include::{restdocdir}/put-api-owner/response-body.adoc[]

****

This operation reports `Ok` or code 200 if the entity was successfully updated.

This operation reports `Created` or code 201 if the entity was successfully created.

This operation reports `Bad Request` or code 400 if the data was not processed.

This operation reports `Conflict` or code 409 if a unique constraint would be violated.

This operation reports `Precondition Failed` or code 412 if data is outdated (invalid ETag).

=== `PATCH /api/owner/{id}`

This operation partially updates an existing entity partially without affecting other properties.
Response is of type `Owner`.

==== `name` attribute

****

.Command
include::{restdocdir}/patch-api-owner-name/curl-request.adoc[]

.Request
include::{restdocdir}/patch-api-owner-name/http-request.adoc[]

.Response
include::{restdocdir}/patch-api-owner-name/response-body.adoc[]

****

This operation reports `Ok` or code 200 if the entity was successfully updated.

This operation reports `Not Found` or code 404 if the entity does not exist.

This operation reports `Bad Request` or code 400 if the data was not processed.

This operation reports `Conflict` or code 409 if a unique constraint would be violated.

This operation reports `Precondition Failed` or code 412 if data is outdated (invalid ETag).

TIP: The descriptions of attributes other than name are omitted for simplicity because they are following the same pattern.

=== `GET /api/owner`

This operation returns persisted entities.
The response is a collection of type `Owner`.

This operation supports advanced query parameters for filtering, e.g.

`?name=Max`::
Find owners with name containing "Max" (case-insensitive)
`?name=Max%`::
Find owners with name starting with "Max" (case-insensitive)
`?address=Street`::
Find owners with address containing "Street" (case-insensitive)
`?contact=@gmx.at`::
Find owners with contact information containing "@gmx.at" (case-insensitive)

This operation supports sorting, e.g.

`?sort=name,asc`::
Sort owners by name in ascending order

This operation supports pagination, e.g.

`?size=10&page=1`::
Find 10 owners on page 1

****

.Command
include::{restdocdir}/get-api-owner/curl-request.adoc[]

.Request
include::{restdocdir}/get-api-owner/http-request.adoc[]

.Response
include::{restdocdir}/get-api-owner/response-body.adoc[]

****

This operation reports `Ok` or code 200 if the data was successfully loaded.

=== `GET /api/owner/search/findAllItem`

This operation returns persisted entities as simplified items for selection purposes.
The response is a collection of type `OwnerItem`.

The items are sorted by name in ascending order.

This operation supports advanced query parameters for filtering.
See `GET /api/owner` for details.

This operation does not support sorting.
The result is always sorted by name in ascending order.

This operation does not support pagination.
It always returns the full filtered result set.

****

.Command
include::{restdocdir}/get-api-owner-item/curl-request.adoc[]

.Request
include::{restdocdir}/get-api-owner-item/http-request.adoc[]

.Response
include::{restdocdir}/get-api-owner-item/response-body.adoc[]

****

The following example shows a filtered request:

****

.Command
include::{restdocdir}/get-api-owner-item-filtered/curl-request.adoc[]

.Request
include::{restdocdir}/get-api-owner-item-filtered/http-request.adoc[]

.Response
include::{restdocdir}/get-api-owner-item-filtered/response-body.adoc[]

****

This operation reports `Ok` or code 200 if the data was successfully loaded.

=== `GET /api/owner/{id}`

This operation returns a single persisted entity.
Response is of type `Owner`.

****

.Command
include::{restdocdir}/get-api-owner-by-id/curl-request.adoc[]

.Request
include::{restdocdir}/get-api-owner-by-id/http-request.adoc[]

.Response
include::{restdocdir}/get-api-owner-by-id/response-body.adoc[]

****

This operation reports `Ok` or code 200 if the data was successfully loaded.

This operation reports `Not Found` or code 404 if the entity does not exist.

=== `DELETE /api/owner/{id}`

This operation deletes a single persisted entity.
Response is of type `Owner`.

****

.Command
include::{restdocdir}/delete-api-owner/curl-request.adoc[]

.Request
include::{restdocdir}/delete-api-owner/http-request.adoc[]

.Response
include::{restdocdir}/delete-api-owner/response-body.adoc[]

****

This operation reports `Ok` or code 200 if the entity was successfully deleted.

This operation reports `Not Found` or code 404 if the entity does not exist.
