:project-dir: ../../../../../../..
:term: JsonJpaRestController
= {term}

A subclass of `{term}` implements the logic for the REST interface.
Operations for the REST interfaces are dynamically generated by _Spring Data REST_.
For reading and writing data, the repositories generated by _Spring Data JPA_ are used.
The scope of the REST API for a resource is determined solely by a repository.

A _Collection Resource_ represents a list of elements.
It is queried with `GET`.
A new _Item Resource_ is created with `POST`.

TIP: See the
https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.collection-resource[Spring Data REST Reference Guide]
in the _Collection Resource_ section for more information.

An _Item Resource_ represents exactly one element.
It is queried with `GET`.
An _Item Resource_ can be modified with `PUT` and `PATCH`.
An _Item Resource_ is deleted with `DELETE`.

TIP: See the
https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.item-resource[Spring Data REST Reference Guide]
in the _Item Resource_ section for more information.

An _Association Resource_ represents a relationship to another _Item Resource_.
It is queried with `GET`.
A new _Item Resource_ is added with `PUT`.
An existing _Item Resource_ is removed with `DELETE`.

TIP: See the
https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.association-resource[Spring Data REST Reference Guide]
in the _Association Resource_ section for more information.

A _Search Resource_ returns all query methods provided by a repository.
It can only be queried with `GET`.

TIP: See the
https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.search-resource[Spring Data REST Reference Guide]
in the _Search Resource_ section for more information.

A _Query Method Resource_ executes a query method.
It can only be queried with `GET`.

TIP: See the
https://docs.spring.io/spring-data/rest/docs/current/reference/html/#repository-resources.query-method-resource[Spring Data REST Reference Guide]
in the _Query Method Resource_ section for more information.

Versioning is a mechanism to ensure data integrity in the database.
The version from the JPA data model is translated into an ETag header.

TIP: See the
https://docs.spring.io/spring-data/rest/docs/current/reference/html/#conditional.etag[Spring Data REST Reference Guide]
in the _Headers_ section for more information.

_Paging_ is a mechanism that returns a large collection resource in parts (pages).
The individual subsets are navigably linked together.

TIP: See the
https://docs.spring.io/spring-data/rest/docs/current/reference/html/#paging-and-sorting[Spring Data REST Reference Guide]
in the _Paging_ section for more information.

_Sorting_ means that the order within a collection resource is determined by a specific sorting criterion.

TIP: See the
https://docs.spring.io/spring-data/rest/docs/current/reference/html/#paging-and-sorting[Spring Data REST Reference Guide]
in the _Sorting_ section for more information.

With a _Projection_, a view can be applied to a resource.
An _Excerpt_ is a _Projection_ that is automatically applied to a _Collection Resource_.

TIP: See the
https://docs.spring.io/spring-data/rest/docs/current/reference/html/#projections-excerpts[Spring Data REST Reference Guide]
in the _Projections_ section for more information.

All write operations run within a transaction.
Flexible callback methods validate and complete incoming records.
They restrict the value range of attributes.
They check dependencies of attributes within the record or with records in other tables.
A save operation can be aborted with an exception.
The goal is not to save records that endanger data integrity through incorrect user input or faulty client programming.

== Properties

=== eventPublisher

The singleton instance of an `ApplicationEventPublisher` is used to provide all database changes as messages for other components in this server process.

=== transactionTemplate

The instance of a `TransactionTemplate` is used to validate incoming data, complete it if necessary, or supplement it before it is written to the database.

== Operations

=== beforeCreateTransaction

[source,java,options="nowrap"]
----
include::{project-dir}/lib/backend-data/src/main/java/esy/rest/JsonJpaRestControllerBase.java[tags=beforeCreateTransaction, indent=0]
----

This operation returns a callback method for a `TransactionTemplate` in a concrete implementation.
The callback method is executed *before* saving a new record.
The method can modify the incoming record.

.Example
[source,java,options="nowrap"]
----
protected Optional<TransactionCallback<Void>> beforeCreateTransaction(@NonNull final V value) {
    return Optional.of(status -> { // <1>
        final ProjektSeq seq = projektSeqRepository.save(ProjektSeq.fromProjekt(value));
        value.setCode(seq.getSeqId()); // <2>
        return null; // <3>
    });
}
----
<1> Here a callback method is defined as a function.

<2> Here a previously generated unique code is stored in the record.

<3> Here `null` is *always* returned. +
The callback method expects a `Void`.

=== afterCreateTransaction

[source,java,options="nowrap"]
----
include::{project-dir}/lib/backend-data/src/main/java/esy/rest/JsonJpaRestControllerBase.java[tags=afterCreateTransaction, indent=0]
----

This operation returns a callback method for a `TransactionTemplate` in a concrete implementation.
The callback method is executed *after* saving a new record.

=== beforeSaveTransaction

[source,java,options="nowrap"]
----
include::{project-dir}/lib/backend-data/src/main/java/esy/rest/JsonJpaRestControllerBase.java[tags=beforeSaveTransaction, indent=0]
----

This operation returns a callback method for a `TransactionTemplate` in a concrete implementation.
The callback method is executed *before* saving an already existing record.
The method can modify the incoming record.

.Example
[source,java,options="nowrap"]
----
protected Optional<TransactionCallback<Void>> beforeSaveTransaction(@NonNull final Projekt value) {
    return Optional.of(status -> {
        projektSeqRepository.findByRefId(value.getId())
                .filter(seq -> seq.getSeqId().equals(value.getCode())) // <1>
                .orElseThrow(() -> new IllegalArgumentException("code invalid")); // <2>
        return null; // <3>
    });
}
----
<1> Here it is checked whether the code from the record exists in a second table.

<2> Here the save operation is aborted with an `IllegalArgumentException` because the code does not exist. +
This ensures data integrity.

<3> Here `null` is *always* returned. +
The callback method expects a `Void`.

=== afterSaveTransaction

[source,java,options="nowrap"]
----
include::{project-dir}/lib/backend-data/src/main/java/esy/rest/JsonJpaRestControllerBase.java[tags=afterSaveTransaction, indent=0]
----

This operation returns a callback method for a `TransactionTemplate` in a concrete implementation.
The callback method is executed *after* saving an already existing record.

=== beforeDeleteTransaction

[source,java,options="nowrap"]
----
include::{project-dir}/lib/backend-data/src/main/java/esy/rest/JsonJpaRestControllerBase.java[tags=beforeDeleteTransaction, indent=0]
----

This operation returns a callback method for a `TransactionTemplate` in a concrete implementation.
The callback method is executed *before* deleting a record.

=== afterDeleteTransaction

[source,java,options="nowrap"]
----
include::{project-dir}/lib/backend-data/src/main/java/esy/rest/JsonJpaRestControllerBase.java[tags=afterDeleteTransaction, indent=0]
----

This operation returns a callback method for a `TransactionTemplate` in a concrete implementation.
The callback method is executed *after* deleting a record.

=== beforeLinkSaveTransaction

[source,java,options="nowrap"]
----
include::{project-dir}/lib/backend-data/src/main/java/esy/rest/JsonJpaRestControllerBase.java[tags=beforeLinkSaveTransaction, indent=0]
----

This operation returns a callback method for a `TransactionTemplate` in a concrete implementation.
The callback method is executed *before* saving a relation in this record. +
The method can modify the incoming record.

=== afterLinkSaveTransaction

[source,java,options="nowrap"]
----
include::{project-dir}/lib/backend-data/src/main/java/esy/rest/JsonJpaRestControllerBase.java[tags=afterLinkSaveTransaction, indent=0]
----

This operation returns a callback method for a `TransactionTemplate` in a concrete implementation.
The callback method is executed *after* saving a relation in this record.

=== beforeLinkDeleteTransaction

[source,java,options="nowrap"]
----
include::{project-dir}/lib/backend-data/src/main/java/esy/rest/JsonJpaRestControllerBase.java[tags=beforeLinkDeleteTransaction, indent=0]
----

This operation returns a callback method for a `TransactionTemplate` in a concrete implementation.
The callback method is executed *before* deleting a relation in this record.

.Example
[source,java,options="nowrap"]
----
protected Optional<TransactionCallback<Void>> beforeLinkDeleteTransaction(final Projekt value, final Object rel) {
    if (value.getBesitzer() == null) { // <1>
        throw new DataIntegrityViolationException("besitzer is null");
    }
    return Optional.empty(); // <2>
}
----
<1> Here the deletion is aborted with an `IllegalArgumentException` if the project still has an owner. +
This ensures data integrity.

<2> No callback method.

=== afterLinkDeleteTransaction

[source,java,options="nowrap"]
----
include::{project-dir}/lib/backend-data/src/main/java/esy/rest/JsonJpaRestControllerBase.java[tags=afterLinkDeleteTransaction, indent=0]
----

This operation returns a callback method for a `TransactionTemplate` in a concrete implementation.
The callback method is executed *after* deleting a relation in this record.
