:includedir: ../../..
:relrootdir: ../../..
= Entity Editor User Interface

An entity editor is a user interface component for managing properties of a single entity through REST endpoints.

== Architecture overview

The lister component is a Svelte component with reactive state management using runes for efficient state management and change detection.
It consists of the following building blocks:

**Component**::
The component defines the UI structure and data binding and manages UI state and user interactions.

**Service**::
The domain-specific service handles HTTP communication with REST operations.
A base service provides generic REST operation implementations with error handling and logging.

== Implementation details

=== Component properties

==== `entityService`

A private reference to a domain-specific service for HTTP communication with REST operations.
You may use more than one service, e.g. for loading extra data used for selection.

TIP: Replace _entity_ with the name of the entity, e.g. `petService`.

==== `entity`

A property of entity to be edited.

TIP: Replace _entity_ with the name of the entity, e.g. `pet`.

==== `visible`

A state tracking the visibility of the editor.

==== `oncreate`

An event callback invoked on successfull creation of the entity.
The changed entity is an argument for the callback.

==== `onupdate`

An event callback invoked on successfull mutation of the entity.
The changed entity is an argument for the callback.

==== `oncancel`

An event published if the edit operation is cancelled.
The entity is unchanged.

=== Component lifecycle

==== populate form

An effect populates the states for editable property of the entity.

.Example from PetEditor
[source,ts,options="nowrap"]
----
include::{includedir}/app/client-svelte/src/main/svelte/pages/client/PetEditor.svelte[indent=0,tags=form]
----

A derived state computes a new entity with editable properties of the editor.
The original entity provides `id` and `version` for mutations.

.Example from PetEditor
[source,ts,options="nowrap"]
----
include::{includedir}/app/client-svelte/src/main/svelte/pages/client/PetEditor.svelte[indent=0,tags=init]
----

==== create an entity

`onSubmitClicked` creates a new entity with new values from the form and hides the editor.
When the service operation completes successfully, the `create` event is emitted with the  entity returned from the service.

.Example from PetEditor
[source,ts,options="nowrap"]
----
include::{includedir}/app/client-svelte/src/main/svelte/pages/client/PetEditor.svelte[indent=0,tags=create]
----

When the service operation fails, a toast with the error message is displayed and the editor remains visible.

Siehe 
xref:{relrootdir}/doc/svelte/entity_service.adoc[Entity Service]
für mehr Informationen.

==== update an entity

`onSubmitClicked` updates an existing entity with new values from the form and hides the editor.
Use the `update` operation if you want to update every property of the entity to the values of this editor and clear all properties not handled in this editor.
Use the `mutate` operation if you want to update only values of this editor and do not update others.
When the service operation completes successfully, the `update` event is emitted with the entity returned from the service.


.Example from PetEditor
[source,ts,options="nowrap"]
----
include::{includedir}/app/client-svelte/src/main/svelte/pages/client/PetEditor.svelte[indent=0,tags=update]
----

When the service operation fails, a toast with the error message is displayed and the editor remains visible.

Siehe 
xref:{relrootdir}/doc/svelte/entity_service.adoc[Entity Service]
für mehr Informationen.

==== cancel editing

`onCancelClicked` emits the `cancel` event with the current entity and hides the editor.

.Example from PetEditor
[source,ts,options="nowrap"]
----
include::{includedir}/app/client-svelte/src/main/svelte/pages/client/PetEditor.svelte[indent=0,tags=cancel]
----
