:includedir: ../..
:relrootdir: ../..
:restdocdir: {includedir}/lib/backend-data/build
= Name of the API

In this section write a brief summary of the model and operations of this controller.
Take in account the names, properties and methods from entity classes, repository interfaces, controller classes and unit tests.

== Model

In this section describe the model of the API.
Take in account the names, properties and methods from entity classes used in the repository interfaces and controller classes.
There is a separate section for each state transfer objects.
Use the include directive and tags to select only relevant properties from entity classes with their types and annotations.
Do not repeat properties from the code fragment in the description of the model section.

Let included code fragments be a major part of the documentation.
Do not repeat information from the code fragment in the text.

== Operations

In this section describe the operations of the API.
There is a separate section for each operation.
The title consists of the name of the method in uppercase letters followed by the relative path.
Briefly describe the purpose of the operation.
Take in account the mapping from exceptions to status codes:

[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-data/src/main/java/esy/app/EsyBackendRestControllerAdvice.java[indent=0,tags=resolveStatus]
----

Create level 2 sections in the following order:

`POST` operation::
Describe with one example if a snippet exists.

`PUT` operation::
Describe with one example if a snippet exists.

`PATCH` operation::
Describe operations for attributes (@Column) with only the first example of the existing snippets and add a `TIP` annotation with other attributes following the same pattern.
Describe operations for collections (@ElementCollection) with only the first example of the existing snippets and add a `TIP` annotation with other collections following the same pattern.
Describe each operation for relations (@ManyToOne, @OneToMany, @ManyToMany) if a snippet exists.
For each operation add a level 3 section with the name of the property.

`GET` operation returning a collection of items::
Describe with one example if a snippet exists.
Explain query parameters and pagination by example.

`GET` operation returning a single item::
Describe with one example if a snippet exists.

`DELETE` operation::
Describe with one example if a snippet exists.

Briefly describe the response codes for each operation.
Take in account the mapping from exceptions to status codes:

[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-data/src/main/java/esy/app/EsyBackendRestControllerAdvice.java[indent=0,tags=resolveStatus]
----

Create a description for at least the following status codes depending on the operation:

`POST` operation::
This operation reports `Created` or code 201 if the entity was successfully created.
This operation reports `Bad Request` or code 400 if the data was not processed.
This operation reports `Conflict` or code 409 if a unique constraint would be violated.

`PUT` operation::
This operation reports `Ok` or code 200 if the entity was successfully updated.
This operation reports `Created` or code 201 if the entity was successfully created.
This operation reports `Bad Request` or code 400 if the data was not processed.
This operation reports `Conflict` or code 409 if a unique constraint would be violated or if data is outdated (invalid ETag).

`PATCH` operation::
This operation reports `Ok` or code 200 if the entity was successfully updated.
This operation reports `Not Found` or code 404 if the entity does not exist.
This operation reports `Bad Request` or code 400 if the data was not processed.
This operation reports `Conflict` or code 409 if a unique constraint would be violated or if data is outdated (invalid ETag).

`GET` operation::
This operation reports `Ok` or code 200 if the data was successfully loaded.

`DELETE` operation::
This operation reports `Ok` or code 200 if the entity was successfully deleted.
This operation reports `Not Found` or code 404 if the entity does not exist.

Let included snippets be a major part of the documentation.
Use snippets for the `curl` command with title `Command`.
Use snippets for the request body with title `Request`.
Use snippets for the response body with title `Response`, except for `No Content` or code 204.

---

TIP: The following rules apply to all areas.

Do not change or add level 1 sections.

A `TIP` annotation provides additional information about behavior that deviates from the standard.
Do not change `TIP` annotations.

Use `NOTE` admonitions to mark prompts for improvement of the documentation.
Update existing `NOTE` admonitions if the prompt changes due to code changes.
