= Name of the API

Write a brief summary of the model and operations of this controller.
Take in account the names of classes, properties and methods from the implementation.

== Model

There is a separate section for each state transfer objects.
Use the include directive and tags to select only relevant properties from entity classes with their types and annotations.
Do not repeat properties from the code fragment in the description of the model section.

Let included code fragments be a major part of the documentation.
Do not repeat information from the code fragment in the text.

== Operations

There is a separate section for each operation.
The title consists of the name of the method in uppercase letters followed by the relative path.
Briefly describe the purpose of the operation.

Create sections in the following order:

`POST` operation::
Describe with one example if a snippet exists.

`PUT` operation::
Describe with one example if a snippet exists.

`PATCH` operation::
Describe operations for attributes with only one example.
Describe each operations for relations if a snippet exists.

`GET` operation returning a collection of items::
Describe with one example if a snippet exists.
Explain query parameters and pagination by example.

`GET` operation returning a single item::
Describe with one example if a snippet exists.

`DELETE` operation::
Describe with one example if a snippet exists.

Briefly describe the response codes for each operation.

Let included snippets be a major part of the documentation.
Use snippets for `curl`, request and response except for `No Content` or code 204.
