:includedir: ../..
:relrootdir: ../..
= Entity Lister User Interface

An entity lister is a user interface component for displaying and managing collections of entities retrieved through REST API operations.
A lister provides functionality for viewing, filtering, creating, updating, and deleting entities in a table-based layout.

== Architecture overview

The lister component is a Svelte component with reactive state management using runes for efficient state management and change detection.
It consists of the following building blocks:

**Component**::
The component defines the UI structure and data binding and manages UI state and user interactions.

**Service**::
The domain-specific service handles HTTP communication with REST operations.
A base service provides generic REST operation implementations with error handling and logging.

== Implementation details

=== Component properties

==== `loading`

A state tracking the loading state for display with a loading spinner.

==== `entity collection`

A state containing the complete entity collection with methods for managing the collection.
Use prefix `all`.

TIP: Replace _entity_ with the name of the entity, e.g. `allPet`.

=== Component lifecylce

==== load collection

`onMount` loads the entity collection when the component is initialized.
`onFilterClicked` loads the entity collection when filter criteria change.

.Example from PetLister
[source,ts,options="nowrap"]
----
include::{includedir}/app\client-svelte\src\main\svelte\pages\client\PetLister.svelte[indent=0,tags=loadAll]
----

Siehe 
xref:{relrootdir}/doc/svelte/entity_service.adoc[Entity Service]
f端r mehr Informationen.

==== create an entity

A click on the add button in the title row of the table opens an inline entity editor for creating a new entity.

Siehe 
xref:{relrootdir}/doc/svelte/entity_editor.adoc[Entity Editor User Interface]
f端r mehr Informationen.

After successful creation, the `afterCreate` callback prepends the returned entity to the entity collection.

.Example from PetLister
[source,ts,options="nowrap"]
----
include::{includedir}/app\client-svelte\src\main\svelte\pages\client\PetLister.svelte[indent=0,tags=afterCreate]
----

If editing is cancelled, the entity collection remains unmodified.

==== update an entity

A click on the edit button in a table row opens an inline entity editor for updating the entity displayed in this row.

Siehe
xref:{relrootdir}/doc/svelte/entity_editor.adoc[Entity Editor User Interface]
f端r mehr Informationen.

After successful creation, the `afterUpdate` callback replaces the returned entity in the collection.

.Example from PetLister
[source,ts,options="nowrap"]
----
include::{includedir}/app\client-svelte\src\main\svelte\pages\client\PetLister.svelte[indent=0,tags=afterUpdate]
----

If editing is cancelled, the entity collection remains unmodified. 

==== remove an entity

A click on the delete button in a table row removes the entity displayed in this row.

.Example from PetLister
[source,ts,options="nowrap"]
----
include::{includedir}/app\client-svelte\src\main\svelte\pages\client\PetLister.svelte[indent=0,tags=remove]
----

Siehe 
xref:{relrootdir}/doc/svelte/entity_service.adoc[Entity Service]
f端r mehr Informationen.

After confirming the prompt, the `afterRemove` callback filters out the entity from the collection.

.Example from PetLister
[source,ts,options="nowrap"]
----
include::{includedir}/app\client-svelte\src\main\svelte\pages\client\PetLister.svelte[indent=0,tags=afterRemove]
----

If deletion is cancelled, the entity collection remains unmodified.
