:includedir: ../../..
:relrootdir: ../../..
= Entity Lister Component

An entity lister is a user interface component for displaying and managing collections of entities retrieved through REST endpoints.
A lister provides functionality for viewing, filtering, creating, updating, and deleting entities in a table-based layout.

== Architecture overview

The lister component is a standalone Angular component with reactive state management using signals for efficient state management and change detection.
It consists of the following building blocks:

**Template**::
The Angular template defines the UI structure and data binding.
It uses DaisyUI and Tailwind for styling and responsive design with mobile first approach.

**Component**::
The Angular component manages UI state and user interactions.

**Service**::
The domain-specific service handles HTTP communication with REST operations.
A base service provides generic REST operation implementations with error handling and logging.

== Implementation details

=== Component properties

==== `destroyRef`

A private reference to a `DestroyRef` instance for cleanup, e.g. rxJs subscriptions.

==== `loading`

A signal tracking the loading state for display with a loading spinner.

==== `filterForm`

A reactive form group for capturing filter criteria used to filter the entity collection if needed.

==== `all<entity>`

A signal containing the complete entity collection with methods for managing the collection.
Use prefix `all` for this collection.

=== Component lifecylce

==== load collection

`onFilterClicked` loads the entity collection when this component gets initialized through an effect in the constructor or when the filter criteria change.

.Example from pet-lister
[source,ts,options="nowrap"]
----
include::{includedir}/app/client-angular/src/main/angular/pages/client/pet-lister/pet-lister.ts[indent=0,tags=onFilterClicked]
----

==== load extra data

`ngOnInit` loads extra data if needed.
Use `forkJoin` to load more than one extra data in parallel, with one shared subscription.

.Example from pet-lister
[source,ts,options="nowrap"]
----
include::{includedir}/app/client-angular/src/main/angular/pages/client/pet-lister/pet-lister.ts[indent=0,tags=ngOnInit]
----

==== create an entity

A click on the add button in the title row of the table opens an inline entity editor for creating a new entity.
After successful creation, the `afterCreate` callback prepends the returned entity to the entity collection.

.Example from pet-lister
[source,ts,options="nowrap"]
----
include::{includedir}/app/client-angular/src/main/angular/pages/client/pet-lister/pet-lister.ts[indent=0,tags=afterCreate]
----

If editing is cancelled, the entity collection remains unmodified.

==== update an entity

A click on the edit button in a table row opens an inline entity editor for updating the entity displayed in this row.
After successful creation, the `afterUpdate` callback replaces the returned entity in the collection.

.Example from pet-lister
[source,ts,options="nowrap"]
----
include::{includedir}/app/client-angular/src/main/angular/pages/client/pet-lister/pet-lister.ts[indent=0,tags=afterUpdate]
----

If editing is cancelled, the entity collection remains unmodified. 

==== remove an entity

A click on the delete button in a table row removes the entity displayed in this row.
After confirming the prompt, the `afterRemove` callback filters out the entity from the collection.

.Example from pet-lister
[source,ts,options="nowrap"]
----
include::{includedir}/app/client-angular/src/main/angular/pages/client/pet-lister/pet-lister.ts[indent=0,tags=afterRemove]
----

If deletion is cancelled, the entity collection remains unmodified.

=== Component routing

The Angular component has a route configuration which is added to `app.routes.ts`.
The route configuration registers all providers needed for this component.

.Example from pet-lister
[source,ts,options="nowrap"]
----
include::{includedir}/app/client-angular/src/main/angular/pages/client/pet.routes.ts[indent=0,tags=lister]
----
