= JsonJpaRepository

The `JsonJpaRepository` interface encapsulates database access using _JPA_.
The repository operations are dynamically generated by _Spring Data JPA_.

== Properties

None

== Operations

=== findAll

[source,java,options="nowrap"]
----
Iterable<T> findAll();
Iterable<T> findAll(Sort sort);
Page<T> findAll(Pageable pageable);
----

This operation returns a list of records.

=== findById

[source,java,options="nowrap"]
----
Optional<T> findById(UUID id);
----

This operation returns exactly one record for the specified `UUID` or nothing.

=== save

[source,java,options="nowrap"]
----
<S extends T> S save(S entity);
----

This operation saves a record.

=== delete

[source,java,options="nowrap"]
----
void delete(T entity);
----

This operation deletes a record.

== Tests

The test approach relies on the concept of component integration with `@SpringBootTest` and verifies database operations with an embedded database.
Liquibase applies all changelog scripts so tables, constraints, indexes, etc. exist.

Tests are isolated using `@Transactional` and `@Rollback(true)`.
Each test builds its own state.
Changes must not persist between tests.

The test approach is based on a defined basic structure.

.Example
[source,text,options="nowrap"]
----
@Tag("slow")
@SpringBootTest
@Transactional
@Rollback(true)
public class PetRepositoryTest {

    @Autowired
    private OwnerRepository ownerRepository;

    @Autowired
    private PetRepository petRepository;

    Pet createWithName(final String name) {
        return Pet.fromJson("""
                {
                    "name":"%s",
                    "born":"2021-04-22",
                    "species":"Cat",
                    "sex":"M"
                }
                """.formatted(name));
    }

    Owner saveOwner(final String name) {
        final var owner = Owner.fromJson("""
                {
                    "name":"%s",
                    "address":"Bergweg 1, 5400 Hallein",
                    "contact":"+43 660 5557683"
                }
                """.formatted(name));
        return ownerRepository.save(owner);
    }

    @ParameterizedTest
    @ValueSource(strings = {
            "Käthe",
            "Jörg",
            "Ümit"
    })
    void savePet(final String name) {
        final var value0 = createWithName(name); <1>
        assertFalse(value0.isPersisted());
        assertEquals(0L, value0.getVersion());
        assertNotNull(value0.getId());
        assertEquals(name, value0.getName());
        assertNotNull(value0.getBorn());
        assertNotNull(value0.getSpecies());
        assertNotNull(value0.getSex());
        assertNull(value0.getOwner());

        final var owner = saveOwner("Max Mustermann");
        final var value1 = petRepository.save(value0.setOwner(owner));
        assertNotNull(value1);
        assertNotSame(value0, value1);
        assertTrue(value1.isPersisted());
        assertEquals(0L, value1.getVersion());
        assertTrue(value1.isEqual(value0));
        assertNotNull(value1.getOwner());
    }

    @Test <2>
    void findPet() {
        final var owner = saveOwner("Max Mustermann");
        final var name = "Odi";
        final var value = petRepository.save(createWithName(name).setOwner(owner));
        assertTrue(petRepository.existsById(value.getId()));
        assertTrue(petRepository.findById(value.getId()).orElseThrow().isEqual(value));
    }

    @Test <3>
    void findPetNoElement() {
        final var uuid = UUID.randomUUID();
        assertFalse(petRepository.existsById(uuid));
        assertFalse(petRepository.findById(uuid).isPresent());
    }

    @Test <4>
    void findAll() {
        final var owner = saveOwner("Max Mustermann");
        final var value1 = petRepository.save(createWithName("Odi").setOwner(owner));
        final var value2 = petRepository.save(createWithName("Tom").setOwner(owner));
        final var value3 = petRepository.save(createWithName("Jerry").setOwner(owner));
        assertEquals(3, petRepository.count());
        final var allValue = petRepository.findAll();
        assertEquals(3, allValue.size());
        assertTrue(allValue.remove(value1));
        assertTrue(allValue.remove(value2));
        assertTrue(allValue.remove(value3));
        assertTrue(allValue.isEmpty());
    }
}
----

<1> Create test data with unique attributes, e.g. the name.
<2> Test for exactly one element.
<3> Test for no element.
<4> Test for a collection of elements.
