= Column for a primary key

== Default Implementation

.Entity
[source,java,options="nowrap"]
----
@Id <1>
@Column(name = "id", nullable = false) <2>
@Getter <3>
@JsonProperty <4> 
private final UUID id; <5>
----

<1> The field is marked with `@Id`.
<2> The field is marked with `@Column`.
<3> The field is marked with `@Getter`.
This allows the current value to be queried.
<4> The field is marked with `@JsonProperty`.
The value is contained in the JSON structure of the REST API.
<5> The field has the data type `UUID`.
The value can also be null.

.Liquibase
[source,xml,options="nowrap"]
----
<column name="id" type="UUID"> <1>
    <constraints nullable="false" primaryKey="true"/> <2>
</column>
----

<1> The column type is `UUID`.
<2> The column is marked as NOT NULL and as the primary key.

Generating a primary key with `UUID` has the advantage over generating a `Long` value from an `autoincrement` column or a database sequence in that the key can be generated not only in the database, but also on the server or even on the client if necessary.

== Tests

=== `{Entity}Test`

Create test data from JSON using `fromJson` method of entity classes.

The `equalsHashcodeToString` test verifies equality operations.

The `withId` test verifies cloning.

=== `{Entity}RepositoryTest`

Assert property value in `save{Entity}` test.

.Example pseudo code
[source,text,options="nowrap"]
----
@Test
void save{Entity}() {
    final var value0 = create...(...);
    assertFalse(value0.isPersisted());
    assertEquals(0L, value0.getVersion());
    assertNotNull(value0.getId());

    final var value1 = {entity}Repository.save(value0);
    assertNotNull(value1); 
    assertNotSame(value0, value1); 
    assertTrue(value1.isPersisted());
    assertEquals(0L, value1.getVersion());
    assertTrue(value1.isEqual(value0));
}
----
