= Column for a version number

== Default implementation

.Entity
[source,java,options="nowrap"]
----
@Version <1>
@Column(name = "version", nullable = false) <2>
@Getter <3>
@JsonIgnore <4> 
private final Long version; <5>
----

<1> The field is marked with `@Version`.
<2> The field is marked with `@Column`.
The field name in the database is always specified as an important note for reviews and documentation.
<3> The field is marked with `@Getter`.
This allows the current value to be queried.
<4> The field is marked with `@JsonIgnore`.
The value is not included in the JSON structure of the REST API.
However, the value is transferred to an `ETAG` header.
<5> The field has the data type `Long`.

.Liquibase
[source,xml,options="nowrap"]
----
<column name="version" type="BIGINT" defaultValue="0"> <1>
    <constraints nullable="false"/> <2>
</column>
----

<1> The column type is `BIGINT` (64-bit integer) with a default value of 0.
<2> The column is marked as NOT NULL.

The property is part of the base class.
This ensures that all objects have the same procedure for maintaining integrity.

The property uses the `Long` type and applies the special `@Version` annotation for optimistic locking.

== `<Entity>Test` approach

Create test data from JSON using `fromJson` method of entity classes.

The `equalsHashcodeToString` test verifies equality operations.

The `withId` test verifies cloning.

== `<Entity>RepositoryTest` approach

.Example pseudo code
[source,text,options="nowrap"]
----
@Test
void save<Entity>() {
    final var value0 = create...(...);
    assertFalse(value0.isPersisted());
    assertEquals(0L, value0.getVersion());
    assertNotNull(value0.getId());

    final var value1 = <entity>Repository.save(value0);
    assertNotNull(value1); 
    assertNotSame(value0, value1); 
    assertTrue(value1.isPersisted());
    assertEquals(0L, value1.getVersion());
    assertTrue(value1.isEqual(value0));
}
----

== `<Entity>GraphqlTest` approach

Do not create a Test.

== `<Entity>RestApiTest` approach

Do not create a Test.
