= Column for a primary key

== Domain story

This implementation guide applies to every entity in the domain that requires a stable, globally unique identifier that can be assigned independently of the database.

Generating a primary key with `UUID` has the advantage over generating a `Long` value from an `autoincrement` column or a database sequence in that the key can be generated not only in the database, but also on the server or even on the client if necessary.

== Default implementation

.Entity
[source,java,options="nowrap"]
----
@Id <1>
@Column(name = "id", nullable = false) <2>
@Getter <3>
@JsonProperty <4> 
private final UUID id; <5>
----

<1> The field is marked with `@Id`.
<2> The field is marked with `@Column`.
<3> The field is marked with `@Getter`.
This allows the current value to be queried.
<4> The field is marked with `@JsonProperty`.
The value is contained in the JSON structure of the REST API.
<5> The field has the data type `UUID`.
The value can also be null.

The property is part of the base class.
This ensures that all objects have the same procedure for maintaining a primary key.

== Liquibase changeset

.Column
[source,xml,options="nowrap"]
----
<createTable tableName="vet"> <1>
    <column name="id" type="UUID"> <2>
        <constraints nullable="false" primaryKey="true"/> <3>
    </column>
    <!-- other columns -->
</createTable>
----

<1> A table is created for the entity.
<2> The column type is `UUID`.
<3> The column is marked as NOT NULL and as the primary key.

== Property initialization

The property is initialized in the base class.

== Property manipulation

The property must not be changed.

== Property verification

The property must not be verified.

== Property serialization

The property is by default part of the JSON structure.

== `<Entity>Test` approach

Create test data from JSON using `fromJson` method of entity classes.

The `equalsHashcodeToString` test verifies equality operations.

The `withId` test verifies cloning.

== `<Entity>RepositoryTest` approach

Do not create a test specifically for this property.

== `<Entity>GraphqlTest` approach

Do not create a test specifically for this property.

== `<Entity>RestApiTest` approach

Do not create a test specifically for this property.
