= Column for type `Enum`

== Default implementation

.Entity
[source,java,options="nowrap"]
----
@NotNull <1>
@Column(name = "sex") <2>
@Getter <3>
@JsonProperty <4>
@Enumerated(EnumType.STRING) <5>
private Sex sex; <6>
----

<1> The field is marked with `@NotNull` validation constraint.
This ensures the value is not null.
<2> The field is marked with `@Column`.
The column name in the database is explicitly specified.
<3> The field is marked with `@Getter`.
This allows the current value to be queried via a getter method.
<4> The field is marked with `@JsonProperty`.
The value is included in the JSON structure of the REST API.
<5> The field is marked with `@Enumerated`.
The value is the enum name as a string value.
<6> The field has an enum data type.
This is a mutable field due to requirements from the JPA provider.

.Liquibase
[source,xml,options="nowrap"]
----
<column name="sex" type="VARCHAR(32)" defaultValue="M"> <1>
    <constraints nullable="false"/> <2>
</column>
----

<1> The column type is `VARCHAR` and stores the enum name as string value.
Choose the length to fit your enum names.
Use a matching default value.
<2> The column is marked as NOT NULL.

== Property initialization

Enum properties are generally not nullable and initialized to a valid default enum name in the constructor.

== Property manipulation

Enum properties are generally not nullable and therefore only changed through REST endpoints.

Enum properties are set through in the `withId` operation during entity cloning.

Add a setter if a controller must be able to update a property directly.

[source,java,options="nowrap"]
----
@JsonIgnore <1>
public Pet setSex(@NonNull final Sex sex) { <2>
    this.sex = sex;
    return this; <3>
}
----

<1> The method is marked with `@JsonIgnore` as it is not part of the JSON API.
<2> The method accepts an enum argument.
<3> The method returns `this` for operation chaining.

== Property verification

Enum properties participate in the `isEqual` method comparison.
Use `Objects#equals`.

Enum properties use only the following validation annotation:

* `@NotNull`: Value must not be null.

The `verify` operation may include custom validation logic when required by the domain.

== Property serialization

Enum properties are by default part of the JSON structure.
Values are serialized as the enum name string.

== `<Entity>Test` approach

Create test data from JSON using `fromJson` method of entity classes.

The `equalsHashcodeToString` test verifies equality operations.

The `withId` test verifies cloning.

The `json<Name>` parameterized test verifies the happy path, e.g.

- `verify` does not throw an exception
- correct deserialization from JSON
- assert property value

.Example from Pet entity
[source,java,options="nowrap"]
----
@ParameterizedTest
@EnumSource(Sex.class)
void jsonSex(final Sex sex) {
    final var value = Pet.fromJson("""
        {
            "name":"Odi",
            "born":"2007-03-09",
            "species":"Dog",
            "sex":"%s"
        }
        """.formatted(sex.name()));
    assertDoesNotThrow(value::verify);
    assertEquals(sex, value.getSex());
}
----

The `json<Name>Constraints` parameterized test verifies constraints, e.g.

- `verify` throws an exception
- invalid values are rejected
- missing values are rejected

.Example from Pet entity
[source,java,options="nowrap"]
----
@ParameterizedTest
@ValueSource(strings = {
        "",
        "X"
})
void jsonSexConstraints(final String text) {
    final var json = """
        {
            "name":"Odi",
            "born":"2007-03-09",
            "species":"Dog",
            "sex":"%s"
        }
        """.formatted(text);
    assertThrows(IllegalArgumentException.class, () -> Pet.fromJson(json).verify());
}
----

== `<Entity>RepositoryTest` approach

.Example pseudo code
[source,text,options="nowrap"]
----
@Test
void save<Entity>() {
    final var value0 = create...(...);
    assertFalse(value0.isPersisted());
    assertEquals(0L, value0.getVersion());
    assertNotNull(value0.getId());
    assertNotNull(value0.get<Name>());

    final var value1 = <entity>Repository.save(value0);
    assertNotNull(value1); 
    assertNotSame(value0, value1); 
    assertTrue(value1.isPersisted());
    assertEquals(0L, value1.getVersion());
    assertTrue(value1.isEqual(value0));
}
----

== `<Entity>GraphqlTest` approach

.Example pseudo code
[source,text,options="nowrap"]
----
@Test
void queryAll<Entity>() {
    final var value = <Entity>.fromJson(...);
    when(<entity>Repository.findAll())
            .thenReturn(List.of(value));
    final var data = graphQlTester
            .document("""
                    {all<Entity>{<name>}}
                    """)
            .execute();
    assertNotNull(data);
    data.path("all<Entity>[0].<name>")
            .hasValue()
            .entity(<Type>.class)
            .isEqualTo(...);
    verify(<entity>Repository).findAll();
    verifyNoMoreInteractions(<entity>Repository);
}
----

== `<Entity>RestapiTest` approach

Update existing `postApi<Entity>` test.
The test verifies the happy path of the POST entity operation.
Add a value for the new property in the payload for the request.
Assert the value of the new property in the response.

Update existing `postApi<Entity>Conflict` test.
The test  verifies the primary key conflict of the POST entity operation.
Add a value for the new property in the payload for the request.
Assert the conflict status.

Update existing `putApi<Entity>` test.
The test  verifies the happy path of the PUT entity operation.
Add a value for the new property in the payload for the request.
Assert the value of the new property in the response.

Add `patchApi<Entity><Name>` test.
The test verifies the happy path of the PATCH entity operation for the new property.
Use the primary key from the `putApi<Entity>` test.

.Example pseudo code
[source,text,options="nowrap"]
----
@Test
@Order(31)
void patchApi<Entity><Name>() throws Exception {
    final var value = "X";
    final var uuid = UUID.fromString(...);
    assertTrue(<entity>Repository.findById(uuid).isPresent());
    mockMvc.perform(patch("/api/<entity>/" + uuid)
                    .content("""
                            {
                                "<name>":"%s"
                            }
                            """.formatted(value))
                    .contentType(MediaType.parseMediaType("application/merge-patch+json"))
                    .accept(MediaType.APPLICATION_JSON))
            .andDo(print())
            .andExpect(status()
                    .isOk())
            .andExpect(content()
                    .contentType("application/json"))
            .andExpect(header()
                    .exists("Vary"))
            .andExpect(header()
                    .exists("ETag"))
            .andExpect(jsonPath("$.id")
                    .value(uuid.toString()))
            .andExpect(jsonPath("$.<name>")
                    .value(value));
}
----

Update existing `getApi<Entity>ById` test.
The test verifies the happy path of the GET entity operation.
Use the primary key from the `putApi<Entity>` test.
Compute the new `ETag` value according to the new test.
Assert the value of the new property in the response.
