= Column for type `String`

== Default implementation

.Entity
[source,java,options="nowrap"]
----
@NotBlank <1>
@Column(name = "name") <2>
@Getter <3>
@JsonProperty <4>
private String name; <5>
----

<1> The field is marked with `@NotBlank` validation constraint.
This ensures the value is not null, not empty, and contains at least one non-whitespace character.
<2> The field is marked with `@Column`.
The column name in the database is explicitly specified.
<3> The field is marked with `@Getter`.
This allows the current value to be queried via a getter method.
<4> The field is marked with `@JsonProperty`.
The value is included in the JSON structure of the REST API.
<5> The field has the data type `String`.
This is a mutable field due to requirements from the JPA provider.

.Liquibase
[source,xml,options="nowrap"]
----
<column name="name" type="VARCHAR(512)" defaultValue=""> <1>
    <constraints nullable="false"/> <2>
</column>
----

<1> The column type is `VARCHAR` with a maximum length with a default value.
<2> The column is marked as NOT NULL.

Omit the default value if the field is nullable.

== Property initialization

`String` properties are typically not nullable and initialized to the empty string in the constructor.

== Property manipulation

`String` properties are typically not nullable and therefore only changed through REST endpoints.

`String` properties are set through in the `withId` operation during entity cloning.

Add a setter if a controller must be able to update a property directly.

[source,java,options="nowrap"]
----
@JsonIgnore <1>
public Enum setName(@NonNull final String name) { <2>
    this.name = name;
    return this; <3>
}
----

<1> The method is marked with `@JsonIgnore` as it is not part of the JSON API.
<2> The method accepts a `String` argument.
<3> The method returns `this` for operation chaining.

== Property verification

`String` properties participate in the `isEqual` method comparison.
Use `Objects#equals`.

`String` properties use only the following validation annotations:

* `@NotNull`: Value must not be null
* `@NotBlank`: Value must be not null, not empty, and contain at least one non-whitespace character.

The `verify` operation may include custom validation logic (e.g., time ranges).

== Property serialization

`String` properties are by default part of the JSON structure.

== `<Entity>Test` approach

Create test data from JSON using `fromJson` method of entity classes.

The `equalsHashcodeToString` test verifies equality operations.

The `withId` test verifies cloning.

The `json<Name>` test verifies the happy path, e.g.

- `verify` does not throw an exception
- correct deserialization from JSON
- assert property value

Use a parameterized tests if values are distinct.

.Example from Vet entity
[source,java,options="nowrap"]
----
@Test
void jsonName() {
    final var name = "Mia Musterfrau";
    final var value = Vet.fromJson("""
        {
            "name":"%s"
        }
        """.formatted(name));
    assertDoesNotThrow(value::verify);
    assertEquals(name, value.getName());
}
----

The `json<Name>Constraints` parameterized test verifies constraints, e.g.

- `verify` throws an exception
- invalid values are rejected
- missing values are rejected

Do not create a test if this properties has no contraints and is nullable.

.Example from Vet entity
[source,java,options="nowrap"]
----
@ParameterizedTest
@ValueSource(strings = {
        "",
        " ",
        "\\t",
        "\\n"
})
void jsonNameConstraints(final String text) {
    final var json = """
        {
            "name":"%s"
        }
        """.formatted(text);
    assertThrows(IllegalArgumentException.class, () -> Vet.fromJson(json).verify());
}
----

== `<Entity>RepositoryTest` approach

.Example pseudo code
[source,text,options="nowrap"]
----
@Test
void save<Entity>() {
    final var value0 = create...(...);
    assertFalse(value0.isPersisted());
    assertEquals(0L, value0.getVersion());
    assertNotNull(value0.getId());
    assertNotNull(value0.get<Name>());

    final var value1 = <entity>Repository.save(value0);
    assertNotNull(value1); 
    assertNotSame(value0, value1); 
    assertTrue(value1.isPersisted());
    assertEquals(0L, value1.getVersion());
    assertTrue(value1.isEqual(value0));
}
----

== `<Entity>GraphqlTest` approach

.Example pseudo code
[source,text,options="nowrap"]
----
@Test
void queryAll<Entity>() {
    final var value = <Entity>.fromJson(...);
    when(<entity>Repository.findAll())
            .thenReturn(List.of(value));
    final var data = graphQlTester
            .document("""
                    {all<Entity>{<name>}}
                    """)
            .execute();
    assertNotNull(data);
    data.path("all<Entity>[0].<name>")
            .hasValue()
            .entity(<Type>.class)
            .isEqualTo(...);
    verify(<entity>Repository).findAll();
    verifyNoMoreInteractions(<entity>Repository);
}
----

== `<Entity>RestapiTest` approach

The `postApi<Entity>` test verifies the happy path of the POST entity operation with a valid value for the new property in the payload for the request.
Assert the value of the new property in the response.

The `postApi<Entity>Conflict` test verifies the error path with unique key constraints of the POST entity operation with a valid value for the new property in the payload for the request.
Assert the conflict status.

The `putApi<Entity>` test verifies the happy path of the PUT entity operation with a valid value for the new property in the payload for the request.
Assert the value of the new property in the response.

The `patchApi<Entity><Name>` test verifies the happy path of the PATCH entity operation with a valid value for the new property in the payload for the request.
Use the entity with the primary key from the `putApi<Entity>` test.

.Example pseudo code
[source,text,options="nowrap"]
----
@Test
@Order(31)
void patchApi<Entity><Name>() throws Exception {
    final var value = "Tom";
    final var uuid = UUID.fromString(...);
    assertTrue(<entity>Repository.findById(uuid).isPresent());
    mockMvc.perform(patch("/api/<entity>/" + uuid)
                    .content("""
                            {
                                "<name>":"%s"
                            }
                            """.formatted(value))
                    .contentType(MediaType.parseMediaType("application/merge-patch+json"))
                    .accept(MediaType.APPLICATION_JSON))
            .andDo(print())
            .andExpect(status()
                    .isOk())
            .andExpect(content()
                    .contentType("application/json"))
            .andExpect(header()
                    .exists("Vary"))
            .andExpect(header()
                    .exists("ETag"))
            .andExpect(jsonPath("$.id")
                    .value(uuid.toString()))
            .andExpect(jsonPath("$.<name>")
                    .value(value));
}
----

The `getApi<Entity>ById` test verifies the happy path of the GET entity operation.
Use the entity with the primary key from the `putApi<Entity>` test.
Compute the new `ETag` value according to the new test.
Assert the value of the new property in the response.
