:includedir: ../../..
:relrootdir: ../../..
= Specification for the database

== Configuration overview

Backend services use a central configuration file for the database.
It is only read when the application starts.

.database.properties
[source,text]
----
include::{includedir}/lib/backend-data/src/main/resources/database.properties[]
----
.configuration
[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-data/src/main/java/esy/app/EsyDatabaseConfiguration.java[tags=configuration,indent=0]
----

A `@PropertySource` annotation tells Spring where to find the properties file.

A `@ComponentScan` annotation tells Spring where to look for controller components.

A `@EntityScan` annotation tells Spring where to look for entity classes.

The `@EnableJpaRepositories` annotation activates the repository support.

The `@EnableTransactionManagement` annotation activates the transaction support.

== Implementation details

=== Liquibase

The service uses _Liquibase_ for creating and migrating the database.
DDL statements are scripted in a special XML format.

.liquibase/changelog.xml
[source,text]
----
include::{includedir}/lib/backend-data/src/main/resources/liquibase/changelog.xml[]
----

Since the execution order of the scripts is relevant, the scripts for the database objects are combined into a changelog script.
The changelog script is executed when the application starts.

Each database object has its own script.
Depending on the current state of the database, scripts are executed and create new database objects.
Scripts that have already been executed on this database are ignored.
