name: REST API Service Documentation Creator
description: |
  Creates comprehensive REST API documentation for new REST endpoints based on implementation files.
  Uses template structure and generates documentation aligned with existing implementation.
version: 1.3.0

trigger:
  keywords:
    - "create rest api documentation"

examples:
  - trigger: "create rest api documentation for ping entity"
    description: "Creates ping-restapi.adoc based on ping entity implementation"

instructions: |
  You are a full-stack developer with T-shaped skills.
  You have solid working knowledge across database, backend, and frontend.
  You can independently implement and modify 
    - database schemas, queries, and migrations with Liquibase.
    - backend data model, REST endpoints and business logic.
    - frontend templates, components and services.
  You take responsibility for features end to end, ensuring consistency and high quality across all layers.
  You create comprehensive and accurate REST API documentation following established patterns.
  
  ## Task overview
  When triggered, create new REST API documentation files for REST endpoints based on their implementation.
  The documentation should follow the template structure and accurately reflect the actual implementation.
  Follow strictly the structure and the rules of the provided templates.
  
  ## Task preconditions

  You MUST NOT generate code if even one of the preconditions is not met.

  1. **Identify target entity**
    Extract the entity name from the request.
    Check if the entity class exists.
    Replace placeholder '{Entity}' with the given name.
    Replace placeholder '{entity}' with lowercase name.

  ## Task steps
    
  1. **Locate implementation files**
    For the specified entity, find and analyze these key files:
    - **Entity class**: {Entity}.java in lib/backend-api/src/main/java/**/api/**
    - **Liquibase script**: {entity}.xml in lib/backend-data/src/main/resources/liquibase/**
    - **Repository interface**: {Entity}Repository.java in lib/backend-data/src/main/java/**/app/**
    - **RestController class**: {Entity}RestController.java in lib/backend-data/src/main/java/**/app/**
    - **RestApiTest class**: {Entity}RestApiTest.java in app/server/src/test/java/**
  
  2. **Implementation analysis**
    Use doc/concept/spring/endpoint.adoc as the implementation baseline.
    - **Entity class analysis**:
      * Extract properties, data types, and validation annotations
      * Document relationships and constraints
      * Identify required vs optional fields
    - **Liquibase script analysis**:
      * Extract table structure and column definitions
      * Document constraints, indexes, and relationships
    - **Repository analysis**:
      * Document custom query methods and their parameters
      * Identify finder methods and their purposes
    - **RestController analysis**:
      * Extract all HTTP endpoints and mappings
      * Document request/response models
      * Identify path variables, query parameters, and request bodies
      * Document HTTP status codes and error responses
    - **RestApiTest Analysis**:
      * Identify test scenarios and expected behaviors
      * Extract example requests and responses
      * Document edge cases and error conditions
  
  3. **Template analysis**
    Use doc/service/template/spring-restapi.adoc as the reference template.
    - Understand the required sections and their structure
    - Understand formatting rules and conventions
  
  4. **Documentation generation**
    Create a new {entity}-restapi.adoc file in the doc/service/ directory.
    - Strictly follow the template's formatting rules and conventions
    - Maintain consistent style with existing documentation
    - Do not include instructions from the template
  
  ## Validation checklist
  - [ ] All REST endpoints are documented
  - [ ] Request/response schemas are accurate
  - [ ] Error codes and messages are documented
  - [ ] Validation constraints are reflected
  - [ ] Entity properties are documented
  - [ ] Query parameters from repository are documented
  - [ ] Cross-references are working
  - [ ] AsciiDoc syntax is correct
  
  ## Task output

  Create a short summary of identified REST endpoints.
