:includedir: ../..
:relrootdir: ../..
= Entity Editor User Interface

An entity editor is a user interface component for managing properties of a single entity through REST API operations.

== Architecture overview

The lister component is a standalone Angular component with reactive state management using signals for efficient state management and change detection.
It consists of the following building blocks:

**Template**::
The Angular template defines the UI structure and data binding.
It uses DaisyUI and Tailwind for styling and responsive design with mobile first approach.

**Component**::
The Angular component manages UI state and user interactions.

**Service**::
The domain-specific service handles HTTP communication with REST operations.
A base service provides generic REST operation implementations with error handling and logging.

== Implementation details

=== Component properties

==== `destroyRef`

A reference to a `DestroyRef` instance for cleanup, e.g. rxJs subscriptions.

==== `entityService`

A reference to the domain-specific service for HTTP communication with REST operations.

TIP: Replace _entity_ with the name of the entity, e.g. `petService`.

==== `entity`

The entity to be edited.

TIP: Replace _entity_ with the name of the entity, e.g. `pet`.

==== `mode`

The mode of the editor, either `create` or `update`.

==== `visible`

A signal tracking the visibility of the editor.

==== `form`

A reactive form group for capturing entity properties.

=== Component lifecylce

==== populate form

`ngOnInit` populates the form with the current entity properties.

.Example from pet-editor
[source,ts,options="nowrap"]
----
include::{includedir}/app\client-angular\src\main\angular\pages\client\pet-editor\pet-editor.ts[indent=0,tags=init]
----

==== create an entity

`onSubmitClicked` creates a new entity with new values from the form and hides the editor.
When the service operation completes successfully, the `create` event is emitted with the  entity returned from the service.

.Example from pet-editor
[source,ts,options="nowrap"]
----
include::{includedir}/app\client-angular\src\main\angular\pages\client\pet-editor\pet-editor.ts[indent=0,tags=create]
----

When the service operation fails, a toast with the error message is displayed and the editor remains visible.

==== update an entity

`onSubmitClicked` updates an existing entity with new values from the form and hides the editor.
When the service operation completes successfully, the `update` event is emitted with the  entity returned from the service.

.Example from pet-editor
[source,ts,options="nowrap"]
----
include::{includedir}/app\client-angular\src\main\angular\pages\client\pet-editor\pet-editor.ts[indent=0,tags=update]
----

When the service operation fails, a toast with the error message is displayed and the editor remains visible.

==== cancel editing

`onCancelClicked` emits the `cancel` event with the current entity and hides the editor.

.Example from pet-editor
[source,ts,options="nowrap"]
----
include::{includedir}/app\client-angular\src\main\angular\pages\client\pet-editor\pet-editor.ts[indent=0,tags=cancel]
----
