:includedir: ../..
:relrootdir: ../..
= Setup Java

This manual specifies the java version and related configurations for this repository.
The project uses only versions with long-term support.
Java is used for the backend server application and for build tooling and tasks.

== Build

.build.gradle
[source,gradle]
----
include::{includedir}/build.gradle[tag=setup-java,indent=0]
----

This configuration sets the java version required to compile the source code (sourceCompatibility) and to run the compiled bytecode (targetCompatibility) for all java based gradle subprojects.

.build.gradle
[source,gradle]
----
include::{includedir}/app/server/build.gradle[tag=setup-java,indent=0]
----

The Paketo buildpack configuration in the `bootBuildImage` task specifies the java version for the container runtime.
It uses a distribution provided by Liberica.

== Github

.build.yml
[source,gradle]
----
include::{includedir}/.github/workflows/build.yml[tag=setup-java,indent=0]
----

The GitHub actions workflow configures java for automated builds and tests.
It uses a distribution provided by Eclipse Temurin (formerly AdoptOpenJDK).
