:includedir: ../..
:relrootdir: ../..
= Setup gradle

This manual contains information on configuring Gradle in this repository.repository.
Gradle is the main build tool in this repository.

Gradle depends on a xref:{relrootdir}/doc/manual/setup-java.adoc[Java] runtime.

== Build

.gradle-wrapper.properties
[source,gradle]
----
include::{includedir}/gradle/wrapper/gradle-wrapper.properties[]
----

This configuration sets the gradle version and other properties required to run build tasks locally.

.settings.gradle
[source,gradle]
----
include::{includedir}/settings.gradle[tags=plugins,indent=0]
----

This configuration shows plugins and their version used in build scripts.

.settings.gradle
[source,gradle]
----
include::{includedir}/settings.gradle[tags=repositories,indent=0]
----

This configuration shows repositories used to load dependencies.

gradlePluginPortal::
Official repository for Gradle plugins.

mavenCentral::
Public repository for Java dependencies.

== Github

.build.yml
[source,gradle]
----
include::{includedir}/.github/workflows/build.yml[tag=setup-gradle,indent=0]
----

The GitHub actions workflow configures gradle for automated builds and tests.

.devcontainer.json
[source,gradle]
----
include::{includedir}/.devcontainer/devcontainer.json[tag=setup-gradle,indent=0]
----

The Github devcontainer adds the gradle feature.
