:includedir: ../../../../../../..
:relrootdir: ../../../../../../..
= Specification for the Endpoints

The service uses a central configuration file for endpoints.
It is only read when the application starts.

.endpoint.properties
[source,text]
----
include::{includedir}/lib/backend-data/src/main/resources/endpoint.properties[]
----

A customizer bean configures `Jackson` for reading and writing JSON structures.

.jacksonCustomizer
[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-data/src/main/java/esy/app/EsyBackendConfiguration.java[tags=jacksonCustomizer,indent=0]
----

A configurer bean configures message converters, argument resolvers, formatters, 
CORS, interceptors, path matching or content negotiation.

.webMvcConfigurer
[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-data/src/main/java/esy/app/EsyBackendConfiguration.java[tags=webMvcConfigurer,indent=0]
----

A customizer bean configures security for static resources and actuator health endpoints for the REST endpoints.

.securityCustomizer
[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-data/src/main/java/esy/app/EsyBackendConfiguration.java[tags=securityCustomizer,indent=0]
----

A customizer bean configures security filters for the REST endpoints.

.securityFilterChain
[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-data/src/main/java/esy/app/EsyBackendConfiguration.java[tags=securityFilterChain,indent=0]
----

A configurer bean configures the behavior of auto-exposed REST endpoints.

.repositoryRestConfigurer
[source,java,options="nowrap"]
----
include::{includedir}/lib/backend-data/src/main/java/esy/app/EsyBackendConfiguration.java[tags=repositoryRestConfigurer,indent=0]
----
